
flowchart TD

    start((Start))
    select[Select a .fits file to analyze]
    data["Accessing Data<br/>• load time data<br/>• load flux data<br/>• load quality data"]
    data_struct[(Fits Data)]

    start --> select
    select --> data
    data --> data_struct







